-- Harden the AI assistant tables and functions reported by Supabase Security Advisor.
-- Review deployment prerequisites in infra/supabase/README.md before applying.

BEGIN;

CREATE SCHEMA IF NOT EXISTS extensions;

DO $migration$
DECLARE
  vector_schema text;
BEGIN
  SELECT namespace.nspname
    INTO vector_schema
    FROM pg_catalog.pg_extension AS extension
    JOIN pg_catalog.pg_namespace AS namespace
      ON namespace.oid = extension.extnamespace
   WHERE extension.extname = 'vector';

  IF vector_schema IS NULL THEN
    CREATE EXTENSION vector WITH SCHEMA extensions;
  ELSIF vector_schema <> 'extensions' THEN
    ALTER EXTENSION vector SET SCHEMA extensions;
  END IF;
END;
$migration$;

GRANT USAGE ON SCHEMA extensions TO service_role;

CREATE TABLE IF NOT EXISTS public.knowledge (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content text NOT NULL,
  slug text NOT NULL,
  type text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  embedding extensions.vector(384) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT knowledge_slug_content_key UNIQUE (slug, content)
);

ALTER TABLE public.knowledge ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.knowledge FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.knowledge TO service_role;

DO $migration$
DECLARE
  knowledge_id_sequence text;
BEGIN
  SELECT pg_catalog.pg_get_serial_sequence('public.knowledge', 'id')
    INTO knowledge_id_sequence;

  IF knowledge_id_sequence IS NOT NULL THEN
    EXECUTE pg_catalog.format(
      'GRANT USAGE, SELECT ON SEQUENCE %s TO service_role',
      knowledge_id_sequence
    );
  END IF;
END;
$migration$;

DO $migration$
BEGIN
  IF pg_catalog.to_regclass('public.assistant_logs') IS NOT NULL THEN
    ALTER TABLE public.assistant_logs ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Allow anonymous reads" ON public.assistant_logs;
    DROP POLICY IF EXISTS "Allow anonymous inserts" ON public.assistant_logs;
    REVOKE ALL PRIVILEGES ON TABLE public.assistant_logs FROM PUBLIC, anon, authenticated;
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.assistant_logs TO service_role;
  END IF;
END;
$migration$;

CREATE OR REPLACE FUNCTION public.match_knowledge(
  query_embedding extensions.vector,
  match_threshold double precision,
  match_count integer
)
RETURNS TABLE (
  id bigint,
  content text,
  slug text,
  type text,
  metadata jsonb,
  similarity double precision
)
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = ''
AS $function$
  SELECT
    knowledge.id,
    knowledge.content,
    knowledge.slug,
    knowledge.type,
    knowledge.metadata,
    1 - (knowledge.embedding OPERATOR(extensions.<=>) query_embedding) AS similarity
  FROM public.knowledge AS knowledge
  WHERE 1 - (knowledge.embedding OPERATOR(extensions.<=>) query_embedding)
    > greatest(least(coalesce(match_threshold, 0.5), 1), -1)
  ORDER BY 1 - (knowledge.embedding OPERATOR(extensions.<=>) query_embedding) DESC
  LIMIT least(greatest(coalesce(match_count, 3), 1), 20);
$function$;

REVOKE ALL PRIVILEGES ON FUNCTION public.match_knowledge(extensions.vector, double precision, integer)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.match_knowledge(extensions.vector, double precision, integer)
  TO service_role;

DO $migration$
BEGIN
  IF pg_catalog.to_regprocedure('public.clean_up_leads()') IS NOT NULL THEN
    ALTER FUNCTION public.clean_up_leads() SET search_path = '';
    REVOKE ALL PRIVILEGES ON FUNCTION public.clean_up_leads() FROM PUBLIC, anon, authenticated;
    GRANT EXECUTE ON FUNCTION public.clean_up_leads() TO service_role;
  END IF;

  IF pg_catalog.to_regprocedure('public.update_leads_updated_at()') IS NOT NULL THEN
    ALTER FUNCTION public.update_leads_updated_at() SET search_path = '';
    REVOKE ALL PRIVILEGES ON FUNCTION public.update_leads_updated_at() FROM PUBLIC, anon, authenticated;
    GRANT EXECUTE ON FUNCTION public.update_leads_updated_at() TO service_role;
  END IF;
END;
$migration$;

COMMIT;
